### PR TITLE
Cart page

### PR DESCRIPTION
**Pull request by athar05**
Added cart page with full functionality

### CODE REVIEW

**Comment by athar05** [comment]
In this PR, the cart functionality has been implemented. The productState tracks the items in the product array, and additionally, two arrays tracking products in cart and wishlist have been added. Everytime a product has been added to the cart, the cart state updates.

Functionalities implemented:
- add item to cart
- move item from cart to wishlist
- remove items from cart
- change quantity

Note:
When an item is moved from the cart to the wishlist, the state tracks the change in wishlist. Currenlty the wishlist front-end has not been implemented and will be tackled in the next PR. 

Live preview: https://incomparable-hamster-43b4d7.netlify.app/

**Review by ShoaibTamboli — COMMENTED** [review]
Ui looks good. 
One thing i observed is while increasing quantity the non discounted price is called.
Instead it should add the discounted price
cart
e

**Comment by Shruthi-Babu** [comment]
There is a bug that needs to be fixed, when all the items added in cart are either deleted or moved away from cart, the final amount section still shows how much was saved with that cart contents even though cart at that time wont be having any products.
image

**Comment by athar05** [comment]
> Ui looks good. One thing i observed is while increasing quantity the non discounted price is called. Instead it should add the discounted price cart e

Fixed. Thanks

**Comment by athar05** [comment]
> There is a bug that needs to be fixed, when all the items added in cart are either deleted or moved away from cart, the final amount section still shows how much was saved with that cart contents even though cart at that time wont be having any products. image

Fixed. Thanks

**Pull request merged**
